### ISSUE TITLE
kube-vipのdaemonset化

### ISSUE THREAD

**Issue by boxp** [boxp/lolice#125]
- 新しいargocd applicationとして追加
- 以下のresourceで追加したい

```
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-vip
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-vip-role
rules:
- apiGroups: [""]
  resources: ["services", "services/status", "endpoints", "configmaps", "nodes"]
  verbs: ["get", "list", "watch", "update"]
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "list", "watch", "create", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-vip-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-vip-role
subjects:
- kind: ServiceAccount
  name: kube-vip
  namespace: kube-system

```

```
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-vip-ds
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: kube-vip
  template:
    metadata:
      labels:
        app: kube-vip
    spec:
      serviceAccountName: kube-vip
      # マスター／コントロールプレーンノードのみに配置
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: Exists
      tolerations:
      - operator: Exists        # 全ての taint を許容
      hostNetwork: true          # VIP をホストネットワークで告知
      containers:
      - name: kube-vip
        image: ghcr.io/kube-vip/kube-vip:v0.8.7
        imagePullPolicy: Always
        args: ["manager"]
        securityContext:
          capabilities:
            add: ["NET_ADMIN", "NET_RAW", "SYS_TIME"]
        env:
        - name: vip_arp           ; value: "true"
        - name: port              ; value: "6443"
        - name: vip_interface     ; value: "eth0"
        - name: vip_cidr          ; value: "32"
        - name: dns_mode          ; value: "first"
        - name: cp_enable         ; value: "true"
        - name: cp_namespace      ; value: "kube-system"
        - name: svc_enable        ; value: "true"
        - name: svc_leasename     ; value: "plndr-svcs-lock"
        - name: vip_leaderelection; value: "true"
        - name: vip_leasename     ; value: "plndr-cp-lock"
        - name: vip_leaseduration ; value: "5"
        - name: vip_renewdeadline ; value: "3"
        - name: vip_retryperiod   ; value: "1"
        - name: address           ; value: "192.168.10.99"
        - name: prometheus_server ; value: ":2112"

```
